projectPath: "..." # path to project if current path is not it
logsPath: "..." # path to folder
testsPath: "..." # path to folder

testLanguage: "Java" # application data
testFramework: "Selenium" # application data
testBrowser: "GoogleChrome" # application data

testExtension: "java" # to identify test files
testFilePostfix: "" # to identify test files
logExtension: "log" # to identify log files

testPrefix: "" # to identify tests within file
testAnnotation: "@Test" # to identify tests within file

groups:
  group_1:
    - path_to_test_file
    - path_to_test_folder
    - name_of_the_test
  group_2:
    - path_to_test_file
    - path_to_test_folder
    - name_of_the_test
exclude: # any tests from selected above that should be skipped
  - path_to_test_file
  - path_to_test_folder

skipTestsWithoutLogs: true # does not analyse tests if their log data were not found